name: s3-depl

on:
    push:
        branches:
            - "*"
            - "!master"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build React App
              run: npm i --no-optional && npm run build
